name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          mkdir web-deploy
          # Copy the build output to the deployment directory
          cp -R build/web/* web-deploy/
          cd web-deploy
          git init
          git config --global user.email "99raia99@gmail.com"
          git config --global user.name "vinciraia99"
          git config --global init.defaultBranch main
          git add .
          git commit -m "Deploy to GitHub Pages: ${{ github.event.head_commit.message }}"
          git branch -M gh-pages
          git push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/vinciraia99/DuckDuckGoMailApp.git" gh-pages
